# Site settings
title: "Nixel - Negocios Inmobiliarios"
sitename: Nixel
author: Nixel
email: nixelnegociosinmobiliarios@gmail.com
description: "Somos profesionales al servicio de tu proyecto de vanguardia. Gestionamos tu inversión, compra, venta, tasación, alquiler. Asesoramiento inmobiliario integral."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.nixelnegociosinmobiliarios.com.ar" # the base hostname & protocol for your site
matricula: "Nixel Negocios Inmobiliarios C. I. N°1855 | C. I. N°2355 | C. I. N°2346"
keywords: "inmobiliaria, rosario, nixel, negocios inmobiliarios, argentina, santa fe, inversiones, alquileres, tasaciones, venta, compra, inmuebles, profesionales, proyectos, asesoramiento"
mainlogo: "/img/logos-01.png"

twitter_username: nixelnegociosinmobiliarios
instagram_username: nixelnegociosinmobiliarios
tiktok_username: nixelnegociosinmobiliarios
facebook_username: nixelnegociosinmobiliarios
facebook_username_link: nixelnegociosinmobiliarios-115626826800373
whatsapp: 5493416508501

telefono:  (341) 650-8501

google_analytics: UA-166786170-1

# Build settings
markdown: kramdown

logo: "./img/logo.svg"

plugins:
  - jekyll-sitemap