# Site settings
title: "Nixel - Negocios Inmobiliarios"
sitename: Nixel
author: Nixel
email: nixelnegociosinmobiliarios@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.nixelnegociosinmobiliarios.com.ar" # the base hostname & protocol for your site

keywords: "inmobiliaria rosario nixel negocios inmobiliarios"
description: "Nixel Negocios inmobiliarios"
mainlogo: "/img/logos-01.png"


twitter_username: nixelnegociosinmobiliarios
instagram_username: nixelnegociosinmobiliarios
facebook_username: nixelnegociosinmobiliarios
facebook_username_link: nixelnegociosinmobiliarios-115626826800373
whatsapp: 5493416508501

telefono:  (341) 650-8501

google_analytics: UA-11111111-1 #UA-166786170-1

# Build settings
markdown: kramdown

logo: "./img/logo.svg"