# Site settings
title: "Nixel - Negocios Inmobiliarios"
sitename: Nixel
author: Nixel
email: nixelnegociosinmobiliarios@gmail.com
description: "Somos profesionales al servicio de tu proyecto de vanguardia. Nuestra experiencia, integridad y conocimiento de las coordenadas son las que nos ayudan a encontrar el rumbo más eficáz. Gestionamos tu inversión, compra, venta, tasación, alquiler. Asesoramiento inmobiliario integral."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.nixelnegociosinmobiliarios.com.ar" # the base hostname & protocol for your site
matricula: "Negocios Inmobiliarios C. I. N°1855"
keywords: "inmobiliaria rosario nixel negocios inmobiliarios"
description: "Nixel Negocios inmobiliarios"
mainlogo: "/img/logos-01.png"


twitter_username: nixelnegociosinmobiliarios
instagram_username: nixelnegociosinmobiliarios
facebook_username: nixelnegociosinmobiliarios
facebook_username_link: nixelnegociosinmobiliarios
whatsapp: 5493416508501

telefono:  (341) 650-8501

google_analytics: UA-166786170-1

# Build settings
markdown: kramdown

logo: "./img/logo.svg"

plugins:
  - jekyll-sitemap